apiVersion: v2
name: tpl
description: Template helm chart for bootstrapping apps
type: application
###! Manually update when ONLY updating chart/subcharts/chart dependencies
###! Otherwise it is updated in ci when appVersion gets an update
###! We _shouldnt_ "release" (triggering version updates) for only chart updates
###! TODO: Somehow add safeguard to not update chart version in ci if manually updated
###! For now tieing tpl and react chart versioning together
version: 0.8.2
###! Follows the version in docker-compose.yml
###! Updated in CI and should not need manual updates
appVersion: "0.10.0-fe9f2cb"
